import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "@/services/SocketProvider";
import React from "react";
import HighOrderComponent from "@/components/HOC";
import DownloadAppBanner from "@/components/DownloadAppBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chat System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" hidden md:block">
          <SocketProvider>
            <HighOrderComponent>{children}</HighOrderComponent>
          </SocketProvider>
        </div>
        <div className=" md:hidden flex items-center justify-center h-screen">
          <DownloadAppBanner />
        </div>
        <div id="modal"></div>
      </body>
    </html>
  );
}
